"""BO4 sound_alias names read straight off the public dump github.com/w28447/-8
(source/tables/sound/<zone>.<lang>.json, all 51 zones x en/fj/all).

Two sources, both checked against the alias id (fnv1a-63 of the bare alias string):
  1. every plaintext "name" field of an alias record whose id lands in pocket 171;
  2. for alias records whose "name" is still #hash_ but whose linked "assetId" file IS already
     named, the alias name derived from that file's stem (basename minus extension, minus a
     trailing _NN / _N / _s variant) - the aliases hashed in the dump because its author's name
     list lacked them, while the file was named on our side by the VO grammar work.

Generated by C:/tmp/bo4_vox/gen_aliases_from_dump_tables.py; names in
bo4_aliases_from_dump_tables.txt."""
import os
here = os.path.dirname(os.path.abspath(__file__))
for l in open(os.path.join(here, "bo4_aliases_from_dump_tables.txt"), encoding="utf-8"):
    if l.strip(): print(l.strip())
