"""New alias pair rules evidenced by an explicit independent witness delta.

Example: python contrib/verified_alias_external_rule_delta_20261010.py --game BLACKOP7 --baseline-file baseline.txt --witness-file independently_verified_aliases.txt --application-file verified_applications.txt --prior-candidate-file earlier_candidates.txt --out logs/new_alias_rules.txt

Inputs contain normalized names or verified hash,name rows. Every baseline,
witness and application name must independently hash into the selected game's
sound_alias capture pool. A witness file must be independently captured source
vocabulary, not descendants generated by this relation. Only the explicit
baseline plus witnesses train rules; application-only names never train them.

The relation is the unchanged alias paired-token method: token distance2..6,
4..18 tokens, both tokens change jointly, three distinct exact sibling frames,
and2..24 observed fillers per frame. Emit ONLY rules whose support was below3
in the frozen baseline and becomes at least3 after the witness delta. Apply
those rules once to the explicit application file. No speculative intermediate
seeds, recursive traversal, independent-slot multiplication, or wider alphabet.

Prior candidate files remove already-tested strings. Shared verified database
readers restore source spellings; all table keys, typed history, current findings
and open-PR claims exclude known results. Probe hits still require normal
confirm_list confirmation with sound_alias selected and this file as --script.
The generator emits name-only candidates so official confirmation retains full64
modern alias hashes. No findings/config changes or submissions are performed.

Initial BLACKOP7 measurement: baseline125367, independent witness delta3353,
application132656 (3936 derived names excluded from training),1086 new directed
rules,24289 unseen candidates,787 unclaimed capture matches. Spent by the exact
baseline/witness/application/prior files, all recorded with SHA256. Outputs are
not a reason to retrain on descendants or run an automatic loop.
"""
import argparse
from collections import Counter, defaultdict
import hashlib
import itertools
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent
while ROOT != ROOT.parent and not (ROOT/'scripts/snapshot.py').is_file():
    ROOT = ROOT.parent
if not (ROOT/'scripts/snapshot.py').is_file():
    raise SystemExit('Cannot find the solver checkout')
sys.path.insert(0, str(ROOT/'scripts'))
import snapshot


def normalized(name):
    return (bool(name) and name.isascii() and name == name.strip().lower()
            and ',' not in name and not any(ord(c) < 32 or ord(c) == 127 for c in name))


def read_names(path, game, held=None):
    data = path.read_bytes()
    names = set()
    for number, row in enumerate(data.decode('utf-8-sig').splitlines(), 1):
        raw, sep, name = row.partition(',')
        if not sep:
            name = row
        if not normalized(name):
            raise ValueError(f'{path.name}:{number}: expected normalized ASCII alias')
        full = snapshot.fnv1a(name, game, 'sound_alias')
        if sep:
            try:
                key = int(raw, 16) & snapshot.ID_MASK
            except ValueError:
                raise ValueError(f'{path.name}:{number}: invalid supplied key')
            if full & snapshot.ID_MASK != key:
                raise ValueError(f'{path.name}:{number}: supplied key does not reproduce')
        if held is not None and full & snapshot.ID_MASK not in held:
            raise ValueError(f'{path.name}:{number}: not held in selected sound_alias pool')
        names.add(name)
    if not names:
        raise ValueError(f'{path.name}: empty input')
    return names, {'file':path.name, 'names':len(names), 'sha256':hashlib.sha256(data).hexdigest()}


def corpus(game):
    names = set(snapshot.table_names('fnv1a_soundbanks_aliases_v2', 'fnv1a_soundbanks_aliases'))
    for top in ['all_names', 'submissions', 'findings']:
        for path in (ROOT/top).rglob('sound_alias*.txt'):
            for row in path.read_text(encoding='utf-8', errors='replace').splitlines():
                raw, sep, name = row.partition(',')
                if not sep or not name:
                    continue
                try:
                    key = int(raw, 16) & snapshot.ID_MASK
                except ValueError:
                    continue
                if snapshot.fnv1a(name, game, 'sound_alias') & snapshot.ID_MASK == key:
                    names.add(name.strip().lower())
    return {name for name in names if normalized(name)}


def excluded_keys(game, aliases):
    known = {key & snapshot.ID_MASK for key in snapshot.known_hashes(game=game)}
    # Submission claims are global by key. Retain every stored table key even
    # when its display spelling cannot be restored or its table is another type.
    paths = list(Path(snapshot.settings.tables_csv()).glob('*.csv'))
    for top in ['all_names', 'submissions', 'findings']:
        paths.extend((ROOT/top).rglob('*.txt'))
    for path in paths:
        with path.open(encoding='utf-8', errors='replace') as handle:
            for row in handle:
                raw, sep, _ = row.partition(',')
                if sep:
                    try:
                        known.add(int(raw.strip(), 16) & snapshot.ID_MASK)
                    except ValueError:
                        pass
    claims = ROOT/'state/claimed.txt'
    if claims.is_file():
        for row in claims.read_text(encoding='utf-8').splitlines():
            try:
                known.add(int(row, 16) & snapshot.ID_MASK)
            except ValueError:
                pass
    known.update(snapshot.fnv1a(n, game, 'sound_alias') & snapshot.ID_MASK for n in aliases)
    return known


def derive(baseline, witnesses, applications, aliases, prior, cap):
    if baseline & witnesses:
        raise ValueError('Witness delta overlaps its frozen baseline')
    train = [(tuple(n.split('_')), n in baseline) for n in sorted(baseline|witnesses)
             if 4 <= len(n.split('_')) <= 18]
    applications = [tuple(n.split('_')) for n in sorted(applications)
                    if 4 <= len(n.split('_')) <= 18]
    candidates, provenance, reports = set(), {}, []
    partial = False
    for gap in range(2,7):
        groups = defaultdict(dict)
        for row, old in train:
            for i in range(len(row)-gap):
                j = i+gap
                groups[row[:i],row[i+1:j],row[j+1:]][row[i],row[j]] = old
        before, after = Counter(), Counter()
        for values in groups.values():
            old = [v for v,b in values.items() if b]
            for fillers, support in [(old,before),(values,after)]:
                if 2 <= len(fillers) <= 24:
                    for a,b in itertools.combinations(sorted(fillers),2):
                        if a[0] != b[0] and a[1] != b[1]:
                            support[a,b] += 1
        rules, support = defaultdict(set), {}
        for (a,b), count in after.items():
            if count >= 3 and before[a,b] < 3:
                rules[a].add(b); rules[b].add(a)
                support[a,b] = support[b,a] = (before[a,b],count)
        controls, previous, initial = 0, 0, len(candidates)
        for row in applications:
            for i in range(len(row)-gap):
                j, old = i+gap, (row[i],row[i+gap])
                for a,b in sorted(rules.get(old,())):
                    changed = list(row); changed[i],changed[j] = a,b
                    name = '_'.join(changed)
                    if name in aliases:
                        controls += 1
                        continue
                    if name in prior:
                        previous += 1
                        continue
                    if len(candidates) >= cap and name not in candidates:
                        partial = True
                        break
                    candidates.add(name)
                    provenance.setdefault(name, {'source':'_'.join(row), 'gap':gap, 'positions':[i,j],
                        'old':old, 'new':[a,b], 'rule_support_before_after':support[old,(a,b)]})
                if partial:
                    break
            if partial:
                break
        reports.append({'gap':gap, 'baseline_supported_rules':2*sum(v>=3 for v in before.values()),
            'new_directed_rules':sum(map(len,rules.values())), 'known_controls':controls,
            'prior_applications_removed':previous, 'new_candidates':len(candidates)-initial})
        if partial:
            break
    return candidates, provenance, reports, partial


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--game', type=str.upper, required=True,
                        choices=sorted(snapshot.MODERN|{'BLKOPS04','BLKOPSCW'}))
    parser.add_argument('--baseline-file', type=Path, required=True)
    parser.add_argument('--witness-file', type=Path, required=True)
    parser.add_argument('--application-file', type=Path, required=True)
    parser.add_argument('--prior-candidate-file', type=Path, action='append', default=[])
    parser.add_argument('--max-candidates', type=int, default=300000)
    parser.add_argument('--out', type=Path, required=True)
    args = parser.parse_args()
    if args.max_candidates < 1:
        parser.error('--max-candidates must be positive')
    shot = snapshot.read(ROOT/'snapshots'/(args.game.lower()+'.ids'))
    if shot.game != args.game:
        parser.error('Capture game differs from selected game')
    held = set(shot.by_pool()['sound_alias'])
    baseline, base_meta = read_names(args.baseline_file,args.game,held)
    witnesses, witness_meta = read_names(args.witness_file,args.game,held)
    applications, app_meta = read_names(args.application_file,args.game,held)
    prior, prior_meta = set(), []
    for path in args.prior_candidate_file:
        names, meta = read_names(path,args.game)
        prior.update(names); prior_meta.append(meta)
    aliases = corpus(args.game)|baseline|witnesses|applications
    candidates, provenance, gaps, partial = derive(baseline,witnesses,applications,aliases,prior,args.max_candidates)
    wanted = held-excluded_keys(args.game,aliases)
    hits = {}
    for name in sorted(candidates):
        key = snapshot.fnv1a(name,args.game,'sound_alias') & snapshot.ID_MASK
        if key in wanted:
            hits.setdefault(key,name)
    report = {'game':args.game, 'baseline':base_meta, 'independent_witness_delta':witness_meta,
        'applications':app_meta, 'application_names_excluded_from_training':len(applications-baseline-witnesses),
        'prior_inputs':prior_meta, 'prior_candidates':len(prior), 'candidate_cap':args.max_candidates,
        'partial':partial, 'new_candidates':len(candidates), 'unclaimed_alias_matches':len(hits),
        'unresolved_alias_ids':len(wanted), 'gaps':gaps}
    args.out.parent.mkdir(parents=True,exist_ok=True)
    args.out.write_text(''.join(n+'\n' for n in sorted(candidates)),encoding='utf-8')
    args.out.with_suffix('.probe_hits.txt').write_text(''.join(n+'\n' for n in sorted(hits.values())),encoding='utf-8')
    args.out.with_suffix('.provenance.json').write_text(json.dumps({n:provenance[n] for n in sorted(hits.values())},indent=2)+'\n',encoding='utf-8')
    args.out.with_suffix('.json').write_text(json.dumps(report,indent=2)+'\n',encoding='utf-8')
    print(json.dumps(report),flush=True)


if __name__ == '__main__':
    main()
